### ISSUE TITLE
Names in Config wrong?

### ISSUE THREAD

**Issue by CloudeLecaw** [Puyodead1/ChunkSpawnerLimiter#7]
I saw in your config your using names like
SKELETON HORSE...

looking into the SpigotAPI site tells me other names like SKELETON_HORSE with an Underscore instead of a space
so what your plugin does?
does it internaly exchange the underscores to spaces? or you just defined it wrong?

You should use these names as these are the official onces

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html

**Comment by Puyodead1** [comment]
That would be a bug lol, I was using Notepad++ to convert the comments to the config variables, must have forgotten about the spaces. Thank you for catching that.
